version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.9
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket employeeartifactstest --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
